# Generated by Django 5.2.4 on 2025-08-03 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='tr-TR', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('error', 'Hata')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Ses Dosyası',
                'verbose_name_plural': 'Ses Dosyaları',
                'ordering': ['-created_at'],
            },
        ),
    ]
