# Generated by Django 5.2.4 on 2025-08-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioupload',
            name='processing_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audioupload',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioupload',
            name='success_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioupload',
            name='successful_chunks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioupload',
            name='total_chunks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
